### ISSUE TITLE
Shorten image file name for TL-WR841N N v9

### ISSUE THREAD

**Issue by stubb** [freifunk-berlin/firmware#178] opened 2014-11-16 21:57 UTC
Just tried to flash a TL-WR841N N v9 with the image file openwrt-ar71xx-generic-tl-wr841n-v9-squashfs-factory.bin. The process failed with an error that the filename is too long. I recommend to shorten it, which was the way to get it going for me.

**Comment by basros** [comment] 2015-07-26 12:12
This issue still exists!

Flashing http://buildbot.berlin.freifunk.net/buildbot/unstable/mpc85xx/568/backbone/openwrt-0.2.0-alpha-mpc85xx-generic-tl-wdr4900-v1-squashfs-factory.bin is impossible without shortening the firmware filename. 
Since our flashing howto only mentions TL-WR841N v8.4 but this issue most probably also applies to every other TP-Link, we should consider updating our documentation/howto or just change firmware filename creation.

**Comment by stubb** [comment] 2015-08-07 10:51
In my opinion using a shorter filename during creation is better because it avoids the error notification and the additional shortening step on the user side.

**Comment by lgierth** [comment] 2015-08-10 10:53
@dangowrt told me this is an issue with most TP-Link devices (or even all of them). OpenWrt started adding its version to the image filename with Chaos Calmer, which now fails the filename length check present in the TP-Link vendor firmware.

So the issue is not actually with TP-Link, but with OpenWrt deliberately breaking the exact purpose of the squashfs-factory images.

**Comment by booo** [comment] 2015-09-07 20:53
Are we happy with the proposed format? An example:

```
kathleen-0.2.0-alpha-cpe210-220-510-520-factory.bin
```

I wonder if the user is confused by the new format and how many howtos we have to change.

**Comment by sarumpaet** [comment] 2015-09-10 12:04
I'm happy with the format. ;)
We have to change URLs for each release anyways (on download page, wiki, config.berlin), so this change isn't extra work really. Even the Howto doesn't link directly.

**Comment by stubb** [comment] 2015-09-10 21:47
The new format has 52 chars in comparison to 56 of the initial format. Did someone checked the max supported length? If the new format is too long I propose to use an 'a' instead of the word 'alpha'.

**Comment by sarumpaet** [comment] 2015-09-11 12:22
i) The "alpha" will be omitted in releases anyways.
ii) You seem to compare the wrong filenames.
Old: openwrt-ar71xx-generic-tl-wr842n-v2-squashfs-factory.bin (57 chars)
New: kathleen-0.2.0-(alpha-)tl-wr842n-v2-factory.bin (40/46 chars)

**Comment by stubb** [comment] 2015-09-11 12:39
Sorry I used kathleen-0.2.0-alpha-cpe210-220-510-520-factory.bin for comparison

**Comment by booo** [comment] 2015-09-12 18:56
As far as I can see we resolved the problem so far. I'm closing the ticket.

**Closed by booo** 2015-09-12 18:56 UTC
Labels: bug
