### ISSUE TITLE
"Sharing internet" without VPN

### ISSUE THREAD

**Issue by mirko** [freifunk-berlin/firmware#212] opened 2015-02-03 11:54 UTC
tl;dr: Don't enforce an VPN when deciding to 'Share internet'.

I will try to haul off as little as possible: I'm pretty sure not allowing to just share your plain internet connection without VPN was more a political rather than a technical decision.
However the situation is changing: there are statements in favour of us, also the 'ISP privilege' got interpreted in favour of us.
Although the VPN was/is a nice workaround, it's not the solution. And it's not Freifunk (if it doesn't have to be). I'd like to encourage people to 'expose' themselves, since the risk of getting sued gets smaller and smaller. Hiding is not necessary anymore.
I'd herewith suggest adding an option for sharing the internet without needing an VPN. Displaying a big warning about potential consequences would probably make sense though :)

**Comment by andrenarchy** [comment] 2015-02-03 12:36
+1 for making the VPN optional!

**Comment by booo** [comment] 2015-02-03 14:16
Related to https://github.com/freifunk-berlin/firmware/issues/144

**Comment by melle** [comment] 2015-02-24 08:25
Would it be sufficient to revert patches/011-luci-freifunk-policyrouting-berlin.patch in case I want to brew my own binary without vpn?

**Comment by cholin** [comment] 2015-02-24 10:14
The easiest way is to add your default route to the `olsr-tunnel` routing table. You may use @booo's [rudimentary hotplug script](https://github.com/freifunk-berlin/firmware/issues/144) for that.

**Comment by sarumpaet** [comment] 2015-10-07 18:22
Duplicate of #144

**Comment by SvenRoederer** [comment] 2017-10-29 02:40
see also https://github.com/freifunk-berlin/firmware/issues/455

**Comment by SvenRoederer** [comment] 2017-10-29 02:44
I outlined a solution in https://github.com/freifunk-berlin/firmware-packages/pull/125

**Comment by SvenRoederer** [comment] 2017-12-25 10:24
this will be implemented by https://github.com/freifunk-berlin/firmware/pull/498 and https://github.com/freifunk-berlin/firmware-packages/pull/125

And it's tested to work by independent testers

**Comment by SvenRoederer** [comment] 2018-01-30 00:32
merged in 8664d2c after testing of at least 2 moths

**Closed** 2018-01-30 00:33 UTC
Labels: enhancement, feed-packages_berlin
