### ISSUE TITLE
build: many make warnings "jobserver unavailable: using -j1."

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/firmware#596] opened 2018-10-16 10:26 UTC
im build-prozess tauchen viele Warnungen von make auf. 

> make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.

Sie scheinen die parallele Ausführung zu betreffen.
Diese Warnungen sind schon eine ganze Weile vorhanden. 

Logfile (master-branch): https://buildbot.berlin.freifunk.net/builders/ramips-mt76x8/builds/205/steps/shell/logs/stdio

**Comment by booo** [comment] 2018-10-22 13:12
Are you sure this is related to our code?

I think this is caused by badly written makefiles from upstream packages.

https://flameeyes.blog/2008/11/16/for-a-parallel-world-case-study-n-4-jobserver-unavailable/

**Comment by lynxis** [comment] 2018-10-26 12:18
AFAIK this is normal. it should come from packages which can not be build in parallel.

**Comment by booo** [comment] 2018-11-03 14:30
As far as I can see this is not related to packages we maintain. Therefore I close this.

**Closed by booo** 2018-11-03 14:30 UTC
Labels: buildsystem

**Comment by SvenRoederer** [comment] 2021-07-06 00:23
Sadly the mentioned build-log was removed but this message is not caused by building OpenWrt-packages. I can see them, when our Makefile is calling "openwrt/scripts/feeds" during the `make -j4 prepare` target ([siehe log](https://github.com/freifunk-berlin/firmware/files/6766552/ffb-build.log)).
Diese Hinweise kommen also offensichtlich von unserer "Ansteuerung" von make.
