### ISSUE TITLE
all: makefiles won't build with vanilla openwrt (master-branch)

### ISSUE THREAD

**Issue by PolynomialDivision** [freifunk-berlin/firmware#817] opened 2020-06-24 06:36 UTC
The current include via [`freifunk-berlin-generic.mk`](https://github.com/freifunk-berlin/firmware-packages/blob/master/freifunk-berlin-generic.mk) will not work with OpenWrt Imagebuilder. The packages will just be empty.

Current workaround is to set a `PKG_VERSION` and do `include $(INCLUDE_DIR)/package.mk` instead of the generic makefile, or for luci apps include `luci.mk`.

Since my priority is vey high that the master builds with imagebuilder correctly, I would like to "revert" the generic.mk until this is fixed and switch temprary to the mentioned solution. I will do a PR.

**Comment by PolynomialDivision** [comment] 2020-06-24 07:01
Related:
https://github.com/freifunk-berlin/firmware/issues/814

**Comment by SvenRoederer** [comment] 2020-06-24 19:35
As a sidenote: the issue is not related to the imagebuilder itself, rather than building the packages at all.

The oldest file made by the buildbot (dated 2.June 2020) also shows this problem. So it's hard to tell when it came up. It affects all files based on OpenWrt-master, which use the freifunk-berlin-generic.mk helper. Not sure what changed upstream, but I normally use PR https://github.com/openwrt/luci/pull/2637 for my build, which are not affected by this issue.
So a quick fix is that you use this PR also, as this is the direction we are heading towards.

**Comment by SvenRoederer** [comment] 2020-08-19 23:15
I updated https://github.com/openwrt/luci/pull/2637 an looking forward to get it merged in openwrt-20.x

**Closed** 2020-10-13 11:51 UTC
Labels: bug, discussion
